---
- name: REDIS_EXPORTER | Copy Daemon script
  template:
    src: redis_exporter.service.j2
    dest: /etc/systemd/system/redis_exporter.service
    mode: 0644
  notify: restart redis_exporter
  when: prometheus_redis_exporter_use_systemd

- name: Copy INIT script to server
  template: src="../templates/redis_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/redis_exporter"  mode="a+x"
  when: not prometheus_redis_exporter_use_systemd|bool

- name: Set INIT status
  service: name=redis_exporter enabled=yes state=restarted
